### ISSUE TITLE
Retrieve English names from OM

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#14]
Can there by an option to allow get_term_by_uri to return English rather than French units in OM?

**Comment by bbartley** [comment]
It does return English names (British spelling)!

```
  <om:Unit rdf:about="&om;litre">
    <rdfs:label xml:lang="en">litre</rdfs:label>
    <rdfs:label xml:lang="nl">liter</rdfs:label>
    <!-- <rdfs:label xml:lang="zh">公升</rdfs:label> -->
    <rdfs:label xml:lang="zh">升</rdfs:label>
    <om:alternativeLabel xml:lang="en">liter</om:alternativeLabel>
    <rdfs:comment xml:lang="en">The litre is a unit of volume defined as 1.0e-3 cubic metre.</rdfs:comment>
    <om:symbol>l</om:symbol>
    <om:alternativeSymbol>L</om:alternativeSymbol>
    <rdf:type rdf:resource="&om;SingularUnit"/>
    <!-- hasDefinition --> <om:hasFactor rdf:datatype="&xsd;float">1.0e-3</om:hasFactor>
    <!-- hasDefinition --> <om:hasUnit rdf:resource="&om;cubicMetre"/>
    <om:hasDimension rdf:resource="&om;volume-Dimension"/>
  </om:Unit>
```
The Dutch spelling (xml:lang="nl") matches English, but only for some metric terms.

It could be possible to return the `om:alternativeLabel`, though this gets tricky as some terms have multiple `alternativeLabels`

**Comment by jakebeal** [comment]
I didn't realized that it was British English!

Well, file this solidly in nice-to-have, I think.

**Comment by bbartley** [comment]
Investigated this further and I am still uneasy about using `om:alternativeLabel` to get English labels.  It is used inconsistently (example, `micrometre` does not have `om:alternativeLabel "micrometer").   Another common unit, `molair` has no American English representation at all, i.e., `molar`.

I think the lightweight option here is to put some special handlers in the OM ontology to do the language conversion, rather than encoding it in the logic of the SPARQL query

**Comment by jakebeal** [comment]
I'd suggest doing that as a patch and also opening an issue on OM to see if we can get the source consistent.

**Comment by bbartley** [comment]
Resolved in https://github.com/SynBioDex/tyto/pull/19
